export const events_abi = [
    {
      type: "constructor",
      inputs: [
        { name: "_nftAddress", type: "address", internalType: "address" },
        { name: "_maxNoOfAttendees", type: "uint256", internalType: "uint256" },
        { name: "_singleTicketPrice", type: "uint256", internalType: "uint256" },
        { name: "_day", type: "uint256", internalType: "uint256" },
        { name: "_month", type: "uint256", internalType: "uint256" },
        { name: "_year", type: "uint256", internalType: "uint256" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "enroll",
      inputs: [{ name: "noOfTickets", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "getDay",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getMonth",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getNoOfBookings",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getNoOfTicketsSold",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getYear",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "i_owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_attendanceNFT",
      inputs: [],
      outputs: [
        { name: "", type: "address", internalType: "contract AttendanceNFT" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_attendeeToNoOfTicketsBooked",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_attendeeToTokenId",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_attendees",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_maxNoOfAttendees",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "s_singleTicketPrice",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "unenroll",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "withdrawEarnings",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    { type: "error", name: "Event__ExceedingMaxAttendance", inputs: [] },
    { type: "error", name: "Event__InsufficientFee", inputs: [] },
    { type: "error", name: "Event__IsNotCurrentlyEnrolled", inputs: [] },
    { type: "error", name: "Event__NoOfTicketsIsZero", inputs: [] },
    { type: "error", name: "Event__NotTheOwner", inputs: [] },
  ];